"use client";

import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState, useTransition, type ReactNode } from 'react';
import { CalendarDays, ClipboardCheck, FolderKanban, Users, History, LayoutDashboard, Pencil, Search, Bug, TriangleAlert, ChevronRight, LogOut, MoreHorizontal, ArrowRight, X, LoaderCircle, CheckCircle2, ListChecks } from 'lucide-react';
import { signOut } from '@/app/auth/actions';
import { updateSprint } from '@/app/planning-actions';
import { ProjectManagement } from './project-management';
import { PersonalTestPerformance } from './personal-test-performance';
import { filterDashboardProjects, type SprintDashboardData } from '@/lib/sprint-dashboard';
import { formatFlexibleDate } from '@/lib/date-format';
import type { CurrentUser, Project, ProjectHistoryEntry, Sprint } from '@/lib/types';

type Props = {groupId:string;groupName:string;sprint:Sprint;data:SprintDashboardData;currentUser:CurrentUser|null;sprintHistory:ProjectHistoryEntry[]};

export function SprintDashboard({groupId,groupName,sprint,data,currentUser,sprintHistory}:Props) {
  const router=useRouter();
  const pathname=usePathname();
  const params=useSearchParams();
  const view=['team','history'].includes(params.get('view') ?? '') ? params.get('view')! : 'overview';
  const [query,setQuery]=useState('');
  const [qaId,setQaId]=useState('');
  const [page,setPage]=useState(0);
  const [showEdit,setShowEdit]=useState(false);
  const [managed,setManaged]=useState<Project|null>(null);
  const [notice,setNotice]=useState('');
  const [historyPage,setHistoryPage]=useState(0);
  const base=`/groups/${groupId}/years/${sprint.year}/sprints`;
  const projectsHref=`${base}/${sprint.id}/projects`;
  const projectHref=(id:string,section='test-cases')=>`/groups/${groupId}/projects/${id}/${section}`;
  const filtered=filterDashboardProjects(data.projects,query,qaId);
  const rows=filtered.slice(page*10,(page+1)*10);
  const summary=data.summary;
  function navigate(next:string) {const search=new URLSearchParams(params.toString()); if(next==='overview')search.delete('view');else search.set('view',next);router.push(`${pathname}${search.size ? `?${search}` : ''}`,{scroll:false});}
  const activity=[...data.moves.map(move=>({id:move.id,createdAt:move.createdAt,actor:move.actorEmail,title:`${String(move.after.name || move.before?.name || 'Project')} · ${String(move.before?.sprint || '')} → ${String(move.after.sprint || '')}`,detail:String(move.after.reason || '')})),...sprintHistory.map(entry=>({id:entry.id,createdAt:entry.created_at,actor:entry.actor_email,title:'แก้ไขข้อมูล Sprint',detail:['name','start_date','end_date','goal','status'].filter(key=>entry.before_data?.[key]!==entry.after_data[key]).map(key=>`${({name:'ชื่อ',start_date:'เริ่ม',end_date:'สิ้นสุด',goal:'เป้าหมาย',status:'สถานะ'} as Record<string,string>)[key]}: ${String(entry.before_data?.[key] ?? '—')} → ${String(entry.after_data[key] ?? '—')}`).join(' · ')}))].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const teamSection=<PersonalTestPerformance data={data.personalPerformance} compact={view==='overview'} onViewAll={()=>navigate('team')}/>;
  return <main className="sd-shell">
    <aside className="sd-sidebar"><Link className="sd-sidebar-brand" href="/groups"><ClipboardCheck size={24}/><span>QA Workspace</span></Link><nav aria-label="เมนู Sprint"><Link href="/groups"><CalendarDays size={18}/>เลือกปี</Link><Link href={`/groups?year=${sprint.year}`}><Users size={18}/>Groups · {sprint.year}</Link><Link href={base}><FolderKanban size={18}/>{sprint.name}</Link><div className="sd-nav-section"><button className={view==='overview' ? 'active' : ''} aria-current={view==='overview' ? 'page' : undefined} onClick={()=>navigate('overview')}><LayoutDashboard size={18}/>ภาพรวม</button><Link href={projectsHref}><FolderKanban size={18}/>Projects</Link><button className={view==='team' ? 'active' : ''} aria-current={view==='team' ? 'page' : undefined} onClick={()=>navigate('team')}><Users size={18}/>ทีม</button><button className={view==='history' ? 'active' : ''} aria-current={view==='history' ? 'page' : undefined} onClick={()=>navigate('history')}><History size={18}/>ประวัติ</button></div></nav><p>Project อยู่ Sprint ปัจจุบัน<br/>ผลงานอยู่ Sprint ต้นกำเนิด</p></aside>
    <div className="sd-main"><header className="sd-topbar"><Link href="/groups">QA Workspace</Link>{currentUser && <div className="sd-user"><span className="sd-avatar">{currentUser.name.slice(0,2).toUpperCase()}</span><span><strong>{currentUser.name}</strong><small>{currentUser.email}</small></span><form action={signOut}><button className="icon-button" title="ออกจากระบบ" aria-label="ออกจากระบบ"><LogOut size={18}/></button></form></div>}</header>
      <div className="sd-content"><nav className="breadcrumb"><Link href="/groups">เลือกปี</Link><ChevronRight size={14}/><Link href={`/groups?year=${sprint.year}`}>ปี {sprint.year} · Groups</Link><ChevronRight size={14}/><Link href={base}>{groupName}</Link><ChevronRight size={14}/><strong>{sprint.name}</strong></nav>
        <div className="sd-heading"><div><div className="sd-title"><h1>{sprint.name}</h1><span className={`sd-sprint-status sd-${sprint.status ?? 'Planned'}`}>{({Planned:'วางแผน',Active:'กำลังดำเนินการ',Completed:'สิ้นสุดแล้ว'})[sprint.status ?? 'Planned']}</span></div><p><CalendarDays size={16}/>{sprint.startDate ? formatFlexibleDate(sprint.startDate,false) : 'ไม่ระบุวันเริ่ม'} — {sprint.endDate ? formatFlexibleDate(sprint.endDate,false) : 'ไม่ระบุวันสิ้นสุด'}</p>{sprint.goal && <p className="sd-goal">เป้าหมาย: {sprint.goal}</p>}</div>{sprint.canManage && <button className="secondary-button" onClick={()=>setShowEdit(true)}><Pencil size={16}/>แก้ไข Sprint</button>}</div>
        {notice && <p className="sd-success" role="status"><CheckCircle2 size={18}/>{notice}</p>}
        <section className="sd-metrics" aria-label="ภาพรวม Sprint">{[{label:'Projects ใน Sprint',value:summary.projects,icon:FolderKanban},{label:'Test cases ทั้งหมด',value:summary.totalCases,icon:ListChecks},{label:'ดำเนินการแล้ว',value:`${summary.progress}%`,icon:CheckCircle2},{label:'Defects ปิดแล้ว / ทั้งหมด',value:`${summary.closedDefects}/${summary.totalDefects}`,icon:Bug}].map(metric=><article key={metric.label}><span className="sd-metric-icon"><metric.icon size={23}/></span><div><strong>{metric.value}</strong><span>{metric.label}</span>{metric.label==='ดำเนินการแล้ว' && <small>{summary.pass+summary.failed+summary.skip} / {summary.totalCases} เคส · รวม Skip</small>}</div></article>)}</section>
        {view==='overview' && <>
          <div className="sd-status-strip">{[['Pass',summary.pass,'pass'],['Failed',summary.failed,'failed'],['Skip',summary.skip,'skip'],['In Progress',summary.inProgress,'in-progress'],['Not Start',summary.notStart,'not-start']].map(([label,count,status])=><span key={label} className={`status-${status}`}><strong>{count}</strong>{label}</span>)}<small>สถานะล่าสุดจากข้อมูลที่บันทึกในเว็บ · ไม่ดึงรูปหรือ Sheets ระหว่างโหลด Dashboard</small></div>
          <section className="sd-panel sd-projects"><div className="sd-section-heading"><div><h2>Projects ใน Sprint <span>{filtered.length} / {data.projects.length}</span></h2><p>สถานะปัจจุบันรวมผลก่อนย้ายเข้ามา · รองรับ QA หลายคนต่อ Project</p></div><div className="sd-filters"><label className="sd-search"><Search size={17}/><input aria-label="ค้นหา Project" placeholder="ค้นหาชื่อ Project…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><select aria-label="กรองตาม QA" value={qaId} onChange={e=>{setQaId(e.target.value);setPage(0);}}><option value="">QA ทั้งหมด</option>{data.team.filter(m=>m.assignedProjects>0).map(m=><option key={m.userId} value={m.userId}>{m.name}</option>)}</select></div></div>
            <div className="sd-table-scroll"><table><thead><tr><th>Project</th><th>QA ที่รับผิดชอบ</th><th>ความคืบหน้า</th><th>Failed</th><th>Defects ปิด/ทั้งหมด</th><th>PO Approval</th><th><span className="sr-only">จัดการ</span></th></tr></thead><tbody>{rows.map(project=><tr key={project.id}><td><Link className="sd-project-name" href={projectHref(project.id)}><FolderKanban size={20}/><span><strong>{project.name}</strong><small>{project.environment}</small></span></Link></td><td><div className="sd-qa-chips">{project.qa.length ? project.qa.map(qa=><span key={qa.userId} title={`${qa.name} · ${qa.email}`}>{qa.name}</span>) : <span className="sd-unassigned">ยังไม่มอบหมาย</span>}</div></td><td><div className="sd-project-progress"><span>{project.counts.pass+project.counts.failed+project.counts.skip} / {project.counts.totalCases} ({project.counts.progress}%)</span><progress value={project.counts.progress} max={100}/></div></td><td className={project.counts.failed ? 'sd-error-count' : ''}>{project.counts.failed}</td><td className={project.counts.openDefects ? 'sd-error-count' : ''}>{project.counts.closedDefects}/{project.counts.totalDefects}</td><td><span className={`sd-approval sd-${project.approval.state}`}>{project.approval.label}</span></td><td><RowMenu project={project} href={projectHref(project.id)} onManage={()=>setManaged(project)}/></td></tr>)}</tbody></table></div>
            {!rows.length && <p className="sd-empty">{data.projects.length ? 'ไม่พบ Project ที่ตรงกับตัวกรอง' : 'ยังไม่มี Project ใน Sprint นี้'}</p>}<footer className="sd-project-footer"><Pager page={page} count={filtered.length} onChange={setPage}/><Link className="primary-button" href={projectsHref}>ดู / เพิ่ม Projects<ArrowRight size={17}/></Link></footer>
          </section>
          <div className="sd-bottom-grid">{teamSection}<section className="sd-panel sd-attention"><div className="sd-section-heading"><h2><TriangleAlert size={20}/>สิ่งที่ต้องติดตาม</h2></div>{data.attention.slice(0,5).map(item=><article key={`${item.kind}-${item.projectId}`}><span className={`sd-attention-icon sd-${item.kind}`}>{item.kind==='failed' ? <Bug size={20}/> : item.kind==='unassigned' ? <Users size={20}/> : <CheckCircle2 size={20}/>}</span><div><strong>{item.kind==='failed' ? `Failed ${item.count} เคส` : item.kind==='unassigned' ? 'ยังไม่มี QA รับผิดชอบ' : `รอ PO รีวิว ${item.count} คน`}</strong><small>{item.projectName}</small></div>{item.kind==='unassigned' ? <button className="secondary-button" onClick={()=>setManaged(data.projects.find(p=>p.id===item.projectId)!)}>ดู<ChevronRight size={15}/></button> : <Link className="secondary-button" href={projectHref(item.projectId,item.kind==='failed' ? 'test-cases' : 'overview')}>ดู<ChevronRight size={15}/></Link>}</article>)}{!data.attention.length && <p className="sd-empty">ไม่มีรายการที่ต้องติดตามจากข้อมูลที่บันทึกไว้</p>}{data.attention.length>5 && <p className="sd-footnote">อีก {data.attention.length-5} รายการ ดูได้จาก Projects ทั้งหมด</p>}</section></div>
          <MovedOut data={data} groupId={groupId}/>
        </>}
        {view==='team' && teamSection}
        {view==='history' && <><section className="sd-panel"><div className="sd-section-heading"><div><h2><History size={20}/>ประวัติ Sprint และการย้าย Projects</h2><p>เก็บผู้แก้ไข เวลา และค่าก่อน–หลัง</p></div></div><div className="sd-history">{activity.slice(historyPage*10,(historyPage+1)*10).map(item=><article key={item.id}><header><strong>{item.title}</strong><time>{formatFlexibleDate(item.createdAt)}</time></header><small>{item.actor || 'ระบบ'}</small><p>{item.detail}</p></article>)}{!activity.length && <p className="sd-empty">ยังไม่มีประวัติการแก้ไขหรือย้าย</p>}</div><Pager page={historyPage} count={activity.length} onChange={setHistoryPage}/></section><MovedOut data={data} groupId={groupId}/></>}
      </div>
    </div>
    {showEdit && <SprintEditDialog key={sprint.updatedAt} sprint={sprint} onClose={()=>setShowEdit(false)} onSaved={()=>{setShowEdit(false);setNotice('บันทึก Sprint และประวัติแล้ว');router.refresh();}}/>}
    {managed && <PlanningDialog title={managed.canManage ? `จัดการ ${managed.name}` : `ประวัติ ${managed.name}`} onClose={()=>setManaged(null)}><ProjectManagement key={managed.id} project={managed} onSaved={saved=>{setManaged(saved);setNotice('บันทึก Project แล้ว');router.refresh();}}/></PlanningDialog>}
  </main>;
}

function Pager({page,count,onChange}:{page:number;count:number;onChange:(page:number)=>void}) {return count>10 ? <div className="sd-pagination"><button className="secondary-button" disabled={!page} onClick={()=>onChange(page-1)}>ก่อนหน้า</button><span>{page+1} / {Math.ceil(count/10)}</span><button className="secondary-button" disabled={(page+1)*10>=count} onClick={()=>onChange(page+1)}>ถัดไป</button></div> : null;}

function MovedOut({data,groupId}:{data:SprintDashboardData;groupId:string}) {return <section className="sd-panel sd-moved-out"><div className="sd-section-heading"><div><h2>Projects ที่ย้ายออก <span>{data.movedOut.length}</span></h2><p>Snapshot ณ ตอนย้าย ไม่รวมในตัวเลขงานปัจจุบันด้านบน</p></div></div>{!data.movedOut.length && <p className="sd-empty">ยังไม่มี Project ที่ย้ายออกจาก Sprint นี้</p>}{data.movedOut.map(move=><article key={move.id}><div><Link href={`/groups/${groupId}/projects/${move.projectId}/test-cases`}><strong>{String(move.after.name || move.before?.name || 'Project')}</strong></Link><p>ย้ายไป <Link href={`/groups/${groupId}/years/${String(move.after.year)}/sprints/${String(move.after.sprintId)}`}>{String(move.after.sprint)} · {String(move.after.year)}</Link></p><small>{move.actorEmail || 'ระบบ'} · {formatFlexibleDate(move.createdAt)}</small></div><div><p>{String(move.after.reason || 'ไม่ระบุเหตุผล')}</p><div className="sd-snapshot-values"><span>{move.snapshot.totalCases ?? 0} เคส</span><span>Pass {move.snapshot.pass ?? 0}</span><span>Failed {move.snapshot.failed ?? 0}</span><span>Skip {move.snapshot.skip ?? 0}</span><span>In Progress {move.snapshot.inProgress ?? 0}</span><span>Not Start {move.snapshot.notStart ?? 0}</span><span>Defects เปิด {move.snapshot.openDefects ?? 0}</span></div></div></article>)}</section>;}

function PlanningDialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog className="sd-dialog" ref={ref} onCancel={onClose} aria-label={title}><header><h2>{title}</h2><button type="button" className="icon-button" onClick={onClose} aria-label="ปิด"><X size={20}/></button></header>{children}</dialog>;}

function SprintEditDialog({sprint,onClose,onSaved}:{sprint:Sprint;onClose:()=>void;onSaved:()=>void}) {
  const [name,setName]=useState(sprint.name);const [start,setStart]=useState(sprint.startDate);const [end,setEnd]=useState(sprint.endDate);const [goal,setGoal]=useState(sprint.goal ?? '');const [status,setStatus]=useState(sprint.status ?? 'Planned');const [error,setError]=useState('');const [pending,startTransition]=useTransition();
  return <PlanningDialog title="แก้ไข Sprint" onClose={()=>{if(!pending)onClose();}}><form className="sd-edit-form" onSubmit={e=>{e.preventDefault();setError('');startTransition(async()=>{const result=await updateSprint({sprintId:sprint.id,groupId:sprint.groupId,name,startDate:start,endDate:end,goal,status,expectedUpdatedAt:sprint.updatedAt ?? ''});if(result.error)setError(result.error);else onSaved();});}}><label className="text-field"><span>ชื่อ Sprint</span><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><div className="two-column-fields"><label className="text-field"><span>วันเริ่ม</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-field"><span>วันสิ้นสุด</span><input type="date" min={start || undefined} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label className="text-field"><span>เป้าหมาย Sprint</span><textarea rows={3} maxLength={2000} value={goal} onChange={e=>setGoal(e.target.value)}/></label><label className="text-field"><span>สถานะ</span><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="Planned">Planned · วางแผน</option><option value="Active">Active · กำลังดำเนินการ</option><option value="Completed">Completed · สิ้นสุดแล้ว</option></select></label><p className="dialog-help">เก็บประวัติทุกการแก้ไข โดยไม่เปลี่ยน ID ของ Sprint หรือผลทดสอบเดิม</p>{error && <p className="form-error" role="alert">{error}</p>}<footer className="dialog-footer"><button type="button" className="secondary-button" disabled={pending} onClick={onClose}>ยกเลิก</button><button type="submit" className="primary-button" disabled={pending}>{pending && <LoaderCircle size={16} className="spin"/>}บันทึก Sprint</button></footer></form></PlanningDialog>;
}

function RowMenu({project,href,onManage}:{project:Project;href:string;onManage:()=>void}) {
  const menu=useRef<HTMLDivElement>(null);
  const id=`project-menu-${project.id}`;
  return <><button type="button" className="icon-button" popoverTarget={id} aria-label={`จัดการ ${project.name}`} onClick={event=>{
    const rect=event.currentTarget.getBoundingClientRect();
    if(menu.current) {menu.current.style.left=`${Math.max(8,Math.min(rect.right-230,window.innerWidth-238))}px`;menu.current.style.top=`${Math.max(8,Math.min(rect.bottom+4,window.innerHeight-120))}px`;}
  }}><MoreHorizontal size={19}/></button><div id={id} popover="auto" ref={menu} className="sd-row-popover" aria-label={`จัดการ ${project.name}`}><Link href={href} onClick={()=>menu.current?.hidePopover()}>เปิด Test cases</Link><button type="button" onClick={()=>{menu.current?.hidePopover();onManage();}}>{project.canManage ? 'แก้ไข / ย้าย / จัดการ QA' : 'ดูประวัติ'}</button></div></>;
}
